# Generated by Django 5.0.3 on 2026-07-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arauth", "0002_alter_captchamodel_create_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captchamodel",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
