# Generated by Django 5.0.3 on 2026-07-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arauth", "0004_alter_captchamodel_create_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="captchamodel",
            name="update_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="captchamodel",
            name="create_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
