# Generated by Django 5.0.3 on 2026-07-25 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arauth", "0005_captchamodel_update_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="captchamodel",
            name="update_time",
        ),
        migrations.AlterField(
            model_name="captchamodel",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 7, 25, 8, 25, 44, 81059, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
