# Generated by Django 5.0.3 on 2026-07-25 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["-pub_time"],
                "verbose_name": "博客",
                "verbose_name_plural": "博客",
            },
        ),
        migrations.AlterModelOptions(
            name="blogcategory",
            options={"verbose_name": "博客分类", "verbose_name_plural": "博客分类"},
        ),
        migrations.AlterModelOptions(
            name="blogcomment",
            options={
                "ordering": ["-pub_time"],
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
            },
        ),
    ]
